// <auto-generated />
using System;
using GoodHamburger.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburger.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524174657_InicializacaoBanco")]
    partial class InicializacaoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburger.Domain.Entities.GrupoOpcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaximoSelecoes")
                        .HasColumnType("int");

                    b.Property<int?>("MinimoSelecoes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<int>("TipoSelecao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GruposOpcoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaximoSelecoes = 3,
                            Nome = "Adicionais",
                            Obrigatorio = false,
                            TipoSelecao = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaximoSelecoes = 1,
                            MinimoSelecoes = 1,
                            Nome = "Ponto da carne",
                            Obrigatorio = true,
                            TipoSelecao = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Tamanho",
                            Obrigatorio = false,
                            TipoSelecao = 1
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Itens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            DataCriacao = new DateTime(2026, 5, 24, 17, 46, 57, 147, DateTimeKind.Utc).AddTicks(9835),
                            Nome = "X Burger",
                            PrecoUnitario = 5.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            DataCriacao = new DateTime(2026, 5, 24, 17, 46, 57, 147, DateTimeKind.Utc).AddTicks(9839),
                            Nome = "X Egg",
                            PrecoUnitario = 4.50m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            DataCriacao = new DateTime(2026, 5, 24, 17, 46, 57, 147, DateTimeKind.Utc).AddTicks(9840),
                            Nome = "X Bacon",
                            PrecoUnitario = 7.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            DataCriacao = new DateTime(2026, 5, 24, 17, 46, 57, 147, DateTimeKind.Utc).AddTicks(9841),
                            Nome = "Batata frita",
                            PrecoUnitario = 2.00m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            DataCriacao = new DateTime(2026, 5, 24, 17, 46, 57, 147, DateTimeKind.Utc).AddTicks(9842),
                            Nome = "Refrigerante",
                            PrecoUnitario = 2.50m,
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.ItemGrupoOpcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrupoOpcaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaximoSelecoes")
                        .HasColumnType("int");

                    b.Property<int?>("MinimoSelecoes")
                        .HasColumnType("int");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GrupoOpcaoId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItensGruposOpcoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11110000-0001-0000-0000-000000000001"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            MaximoSelecoes = 3,
                            Obrigatorio = false
                        },
                        new
                        {
                            Id = new Guid("11110000-0002-0000-0000-000000000002"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            MaximoSelecoes = 1,
                            MinimoSelecoes = 1,
                            Obrigatorio = true
                        },
                        new
                        {
                            Id = new Guid("11110000-0003-0000-0000-000000000003"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            MaximoSelecoes = 1,
                            Obrigatorio = false
                        },
                        new
                        {
                            Id = new Guid("11110000-0004-0000-0000-000000000004"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            MaximoSelecoes = 1,
                            Obrigatorio = false
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Opcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrupoOpcaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecoAdicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoOpcaoId");

                    b.ToTable("Opcoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0001-0000-0000-000000000001"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nome = "Bacon extra",
                            PrecoAdicional = 2.00m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0002-0000-0000-000000000002"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nome = "Queijo extra",
                            PrecoAdicional = 1.50m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0003-0000-0000-000000000003"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nome = "Molho barbecue",
                            PrecoAdicional = 1.00m
                        },
                        new
                        {
                            Id = new Guid("b0000000-0001-0000-0000-000000000001"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nome = "Mal passada",
                            PrecoAdicional = 0.00m
                        },
                        new
                        {
                            Id = new Guid("b0000000-0002-0000-0000-000000000002"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nome = "Ao ponto",
                            PrecoAdicional = 0.00m
                        },
                        new
                        {
                            Id = new Guid("b0000000-0003-0000-0000-000000000003"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nome = "Bem passada",
                            PrecoAdicional = 0.00m
                        },
                        new
                        {
                            Id = new Guid("c0000000-0001-0000-0000-000000000001"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nome = "Pequeno",
                            PrecoAdicional = -2.00m
                        },
                        new
                        {
                            Id = new Guid("c0000000-0002-0000-0000-000000000002"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nome = "Médio",
                            PrecoAdicional = 0.00m
                        },
                        new
                        {
                            Id = new Guid("c0000000-0003-0000-0000-000000000003"),
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrupoOpcaoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nome = "Grande",
                            PrecoAdicional = 3.00m
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DescontoPercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ObservacaoGeral")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("PromocaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PedidoItemOpcao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeOpcao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OpcaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("PedidoItemId");

                    b.ToTable("PedidoItensOpcoes", (string)null);
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@goodhamburger.com",
                            Nome = "Administrador",
                            Perfil = 1,
                            SenhaHash = "$2a$12$MxtoBxZcMUBXeCfpog03a.SbV2eeH/kbRsBGmK8oY.1rIMtgF6Uti"
                        });
                });

            modelBuilder.Entity("Promocao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItensObrigatoriosIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RequisitosTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promocao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d471"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItensObrigatoriosIds = "",
                            Nome = "Combo Completo",
                            Percentual = 0.20m,
                            RequisitosTipo = "1,3,2"
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d472"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItensObrigatoriosIds = "",
                            Nome = "Lanche e Refri",
                            Percentual = 0.15m,
                            RequisitosTipo = "1,3"
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d473"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItensObrigatoriosIds = "",
                            Nome = "Lanche e Batata",
                            Percentual = 0.10m,
                            RequisitosTipo = "1,2"
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.ItemGrupoOpcao", b =>
                {
                    b.HasOne("GoodHamburger.Domain.Entities.GrupoOpcao", "GrupoOpcao")
                        .WithMany()
                        .HasForeignKey("GrupoOpcaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoodHamburger.Domain.Entities.Item", "Item")
                        .WithMany("GruposOpcoes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoOpcao");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Opcao", b =>
                {
                    b.HasOne("GoodHamburger.Domain.Entities.GrupoOpcao", "GrupoOpcao")
                        .WithMany("Opcoes")
                        .HasForeignKey("GrupoOpcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoOpcao");
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("GoodHamburger.Domain.Entities.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PedidoItemOpcao", b =>
                {
                    b.HasOne("GoodHamburger.Domain.Entities.PedidoItem", null)
                        .WithMany("OpcoesSelecionadas")
                        .HasForeignKey("PedidoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.GrupoOpcao", b =>
                {
                    b.Navigation("Opcoes");
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Item", b =>
                {
                    b.Navigation("GruposOpcoes");
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PedidoItem", b =>
                {
                    b.Navigation("OpcoesSelecionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
